### ISSUE TITLE
Context: eager4omdBuilder

### ISSUE THREAD

**Issue by remigium** [slawascichy/hgdb-grafana-datasource#2]
Czemu eager4omdBuilder to String? Ma wartości boolean

**Comment by slawascichy** [comment]
Tak jak napisałem w zadaniu #1 - zaszłość historyczna w API, kompatybilność wstecz. Nie uznałem za konieczne by to zmienić. Jeżeli to przeszkadza, to załóż zadanie w https://github.com/slawascichy/hgdb/issues, ale przyznam szczerze, że ze względu na natłok prac zadanie będzie o najniższym priorytecie.
