### ISSUE TITLE
OAuth: required parameters

### ISSUE THREAD

**Issue by remigium** [slawascichy/hgdb-grafana-datasource#3]
1. Jakie znaczenie mają pola user i password w ConfigEditor? Czy w ogóle są potrzebne przy OAuth? Mam wrażenie, że potrzebne są jedynie client id i client secret
2. btw. czy client Secret nie powinien także trafić do SecureJsonData?
3. Po co są userRoles tam? Jakieś ograniczenia w dostępie do danych?

**Comment by remigium** [comment]
Tu jest definicja oczekiwan wzgledem plugin.json
`          "tokenAuth": {
            "type": "object",
            "description": "For data source plugins. Token authentication section used with an OAuth API.",
            "additionalProperties": false,
            "properties": {
              "url": {
                "type": "string",
                "description": "URL to fetch the authentication token."
              },
              "scopes": {
                "type": "array",
                "description": "The list of scopes that your application should be granted access to.",
                "items": {
                  "type": "string"
                }
              },
              "params": {
                "type": "object",
                "description": "Parameters for the token authentication request.",
                "additionalProperties": false,
                "properties": {
                  "grant_type": {
                    "type": "string",
                    "description": "OAuth grant type"
                  },
                  "client_id": {
                    "type": "string",
                    "description": "OAuth client ID"
                  },
                  "client_secret": {
                    "type": "string",
                    "description": "OAuth client secret. Usually populated by decrypting the secret from the SecureJson blob."
                  },
                  "resource": {
                    "type": "string",
                    "description": "OAuth resource"
                  }
                }
              }
            }
          },`
Czy to oznacza, że  parametry username i password sa ignorowane i token jest wydawany na podstawie client_id/client_secret?

**Comment by slawascichy** [comment]
Hmmm... Swego czasu jak czytałem i implementowałem mechanizm OAuth, to wydawało mi się że to zależy od "grant_type". W zadaniu  #1 już pisałem https://www.oauth.com/oauth2-servers/access-tokens/password-grant/. Tak zaimplementowałem usługę OAuth, że u mnie wszystkie pola są wymagane. Jeżeli uważasz, że praktyczniej byłoby inaczej to proszę otwórz zadanie w https://github.com/slawascichy/hgdb/issues i poprawię :)

**Comment by slawascichy** [comment]
> btw. czy client Secret nie powinien także trafić do SecureJsonData?

Możliwe, że tak, chociaż z punktu widzenia mojej implementacji OAuth większe znaczenie ma nazwa użytkownika i jego hasło. Z mojej praktyki aplikacji mobilnych wynika, że clientId oraz client Secret są zaszywane w kodzie klienta. Przyznam się, że nie uważam tego za super bezpieczne, a jak nie jest bezpieczne, to nie wiem czy jest sens bardziej zabezpieczać.

**Comment by slawascichy** [comment]
> Po co są userRoles tam? Jakieś ograniczenia w dostępie do danych?

Tak, o te dane jest oparty mechanizm uprawnień dostępu do danych, zobacz: https://hgdb.org/confluence/pages/viewpage.action?pageId=1605721

**Comment by remigium** [comment]
czy możesz sprawdzić, czy widać polaczenia ode mnie? Teoretycznie wykonuje testDatasource i wszystko jest na zielono - ale nie jestem pewien w 100% kodu, wiec może być tak, ze zwraca sukces mimo, ze powinien być błąd

**Comment by slawascichy** [comment]
Jeśli chodzi o czas ekspiracji tokena, to zobacz odpowiedź usługi:
```json
{
   "token_type": "bearer",
   "access_token": "45b52b54950f4fdf34986c866fc21515945c7ae1",
   "expires_in": 3600,
   "expires_on": "1656353736",
   "scope": "mrc-user,mrc-useradmin",
   "refresh_token": "50682ceb779af65f492e830686fbd8c7f9b414a6"
}
```
Pole expires_in jest standardowym polem odpowiedzi - czas życia w sekundach, dodałem pole expires_on - data w milisekundach aby łatwiej było zrobić mechanizm automatycznego odświeżania token'a.

**Comment by remigium** [comment]
Sprawa jest  jasna; cała obsługa OAuth jest automatyczna
kluczowe jest skonfigurowanie routes np.
"routes": [
    {
      "path": "mercury-oauth",
      "url": "{{ .JsonData.serverUrl }}",
      "tokenAuth": {
        "url": "{{ .JsonData.accessTokenURI }}",
        "params": {
          "grant_type": "password",
          "username": "{{ .JsonData.username }}",
          "password": "{{ .SecureJsonData.ownerPassword }}",
          "client_id": "{{ .JsonData.clientId }}",
          "client_secret": "{{ .SecureJsonData.clientSecret }}",
          "scope": "{{ .JsonData.scope }}"
        }
      }
    },
    {
      "path": "mercury",
      "url": "{{ .JsonData.serverUrl }}",
      "headers": []
    }
  ],
To co trafia do params, jest przekazywane do serwera - i to juz wymagania HgDB a nie standardzik
