### ISSUE TITLE
Paths

### ISSUE THREAD

**Issue by remigium** [slawascichy/hgdb-grafana-datasource#4]
Pobranie tokena jest pod https://testcluster.hgdb.io/mercury-ws-app/rest/token
testDatasource pod https://testcluster.hgdb.io/mercury-ws-app/rest/service/CaseBusinessRest/echo
getAllCaseTypes pod https://testcluster.hgdb.io/mercury-ws-app/restServices/TypeCaseRest.getAllCaseTypes

Czy testDatasource nie powienien byc takze pod https://testcluster.hgdb.io/mercury-ws-app/restServices/?

**Comment by remigium** [comment]
Przypuszczam, ze ma sens umieszczenie pobrania tokena w innej galezi (bo mozna blokowac ruch do uslug i pozwolic na probe pobrania tokena kazdemu.
Ale chyba juz cala reszta powinna byc pod jedna galezia - chyba, ze chcesz je dzielic jakos - pod katem funkcjonalnosci czy jakiegos innego kryterium

**Comment by slawascichy** [comment]
> Czy testDatasource nie powienien byc takze pod https://testcluster.hgdb.io/mercury-ws-app/restServices/?

Wcześniej się nad tym zastanawiałem i długo myślałem, ale jest to dostęp do opisu API. Nie ma tam dostępu do danych. To jakby rozszerzenie dokumentacji usług. 
Doszedłem do wniosku, że dodatkowa ochrona jest to niepotrzebna i ogranicza dostęp do poznania produktu. Poza tym, jak zrobię Swagger, to dostęp do niego też nie będzie chroniony. Ma on mechanizmy do budowania i uwierzytelniania requestów.

**Comment by slawascichy** [comment]
> Przypuszczam, ze ma sens umieszczenie pobrania tokena w innej galezi (bo mozna blokowac ruch do uslug i pozwolic na probe pobrania tokena kazdemu. Ale chyba juz cala reszta powinna byc pod jedna galezia - chyba, ze chcesz je dzielic jakos - pod katem funkcjonalnosci czy jakiegos innego kryterium

Tak, tak myślałem by do tego była inna gałąź. Podczas pierwszej implementacji chciałem by po prostu mi to zadziałało i pewnie nie do końca trzymałem się tej zasady.

**Comment by remigium** [comment]
czy pod galezia rest w zasadzie jest tylko testDatasource?
i cala reszta pod restServices?

**Comment by slawascichy** [comment]
W restServices jest tylko dostęp o opisu API. Tam znajdziemy WADL usług, np. https://testcluster.hgdb.io/mercury-ws-app/restServices/CaseSearchExtRest.wadl. 
Endpointy są w  rest/service (poniżej opis WADL usługi):
![image](https://user-images.githubusercontent.com/42983334/176128041-8485ae52-e407-4568-8d66-99b2e20f1b31.png)

**Comment by remigium** [comment]
czyli istotne ścieżki, to:

- URL/mercury-ws-app/rest/token - pobieranie tokena OAuth
- URL/mercury-ws-app/rest/service - usługi
